@password=123456

###
GET http://localhost:62519/api/user?username=jack HTTP/1.1
Authorization: Chat-eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJmZjgwODA4MTczOTA4MzMyMDE3MzkwODQxMmFlMDAwMSIsInN1YiI6ImphY2siLCJhdXRob3JpdGllcyI6WyJHZW5lcmFsVXNlciJdLCJpYXQiOjE2MDc2MDU0NzcsImV4cCI6MTYwNzYwOTA3N30.Kx2j3u0dN8OZw807BZGjcuiwW44xyW4f8944iv_-HcO5Lkonwyx1Cl6Jcqfiqo2HIjZ4wnpWDS0lBbzx0WWDbw
###
POST http://localhost:62519/api/user/login HTTP/1.1
Content-Type: application/json

{
  "username": "jack",
  "password": "111111"
}

###
POST http://localhost:62519/api/user/token HTTP/1.1
Content-Type: application/json

{
  "username": "jack",
  "password": "111111"
}