version: "3.7"
services:
  mysql:
    image: 'mysql:5.7'
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sort_buffer_size=8M']

  chat:
    image: ${DOCKER_REGISTRY}/chat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "62519:62519"
      - "62520:62520"
    env_file: .env
    networks:
      - backend
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  backend:
    driver: bridge

#volumes:
#  chatlog: