version: "3.3"
services:
  mysql:
    image: 'mysql:5.7'
    volumes:
      - /data/mysql:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sort_buffer_size=8M']
  mongodb1:
    image: mongo
    restart: always
    container_name: mongo1
    volumes:
      - /data/mongo1:/data/db
      - /data/mongoenv/mongodb.key:/data/mongodb.key
      - /data/mongoenv/setup.sh:/data/setup.sh
    ports:
      - 27017:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    networks:
      - backend
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
  mongodb2:
    image: mongo
    restart: always
    container_name: mongo2
    volumes:
      - /data/mongo2:/data/db
      - /data/mongoenv/mongodb.key:/data/mongodb.key
      - /data/mongoenv/setup.sh:/data/setup.sh
    ports:
      - 27018:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    networks:
      - backend
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
  mongodb3:
    image: mongo
    restart: always
    container_name: mongo3
    volumes:
      - /data/mongo3:/data/db
      - /data/mongoenv/mongodb.key:/data/mongodb.key
      - /data/mongoenv/setup.sh:/data/setup.sh
    ports:
      - 27019:27017
    env_file: .env
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
networks:
  backend:
    driver: bridge