spring:
  application:
    name: chat
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  messages:
    basename: i18n.message
  profiles:
    active: dev
server:
  port: 62519
nettyserver:
  port: 62520

chat:
  appId: appId
  appKey: appKey
  masterSecret: masterSecret
  url: http://sdk.open.api.igexin.com/apiex.htm

# JWT配置
jwt:
  signKey: 123456
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Chat-
  issuer: chat
  expiration: 86400000
