spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${CHAT_HOST:mysql}:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:123456}
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://chat:123456@${CHAT_HOST:mongodb1}:27017,${CHAT_HOST:mongodb2}:27017,${CHAT_HOST:mongodb3}:27017/chat?replicaSet=mongos
  redis:
    host: ${REDIS_HOST:redis}
    port: 6379
    password: ${REDIS_PASSWORD:111111}
    database: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

logging.level:
  org.springframework.data.mongodb.core: DEBUG
  com.dhy.chat: DEBUG

