spring:
  application:
    name: chat
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  messages:
    basename: i18n.message
  profiles:
    active: ${chat-active:dev}
server:
  port: 62519
nettyserver:
  port: 62520

chat:
  appId: ${chat-appId}
  appKey: ${chat-appKey}
  masterSecret: ${chat-masterSecret}
  url: http://sdk.open.api.igexin.com/apiex.htm

app:
  # JWT配置
  jwt:
    key: ${JWT_KEY}
    refreshKey: ${JWT_REFRESH_KEY}
    # HeaderKEY
    tokenHeader: Authorization
    # Token前缀字符
    tokenPrefix: Chat-
    accessTokenExpireTime: 3600000
    refreshTokenExpireTime: 2592000000
