spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.170.97:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://chat:123456@47.107.170.97:27017,47.107.170.97:27018,47.107.170.97:27019/chat?replicaSet=mongos

# JWT配置
jwt:
  signKey: 123456
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Chat-
  issuer: chat
  expiration: 86400000

logging.level.org .springframework.data.mongodb.core: DEBUG
