spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.170.97:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://chat:admin@47.107.170.97:27017,47.107.170.97:27018,47.107.170.97:27019/chat?replicaSet=mongos

logging.level.org .springframework.data.mongodb.core: DEBUG
